'use strict';
const $=id=>document.getElementById(id);let token=sessionStorage.getItem('medivan-token')||'',state=null,grid=null,selected=null,driveTimer=null,cameraURL=null;
$('token').value=token;
async function api(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'X-MediVan-Token':token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok){let e=await r.json();throw Error(e.error||r.statusText)}return r}
function notice(text,bad=false){$('notice').textContent=text;$('notice').style.color=bad?'#ff9aa3':'#9fe4d3'}
async function act(action,data={}){try{await api('action',{action,data});notice('Command accepted: '+action);await refresh()}catch(e){notice(e.message,true)}}
$('connect').onclick=()=>{token=$('token').value.trim();sessionStorage.setItem('medivan-token',token);refresh()};
$('stop').onclick=()=>act('estop');document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));
const point=()=>({x:Number($('x').value),y:Number($('y').value)});
$('save-location').onclick=()=>act('location',{...point(),name:$('name').value});
$('enqueue').onclick=()=>act('enqueue',{...point(),name:$('locations').value||$('name').value});
$('pose').onclick=()=>act('set_pose',{x:Number($('pose-x').value),y:Number($('pose-y').value),yaw:Number($('pose-yaw').value)});
$('dock').onclick=()=>act('dock',{supervised:$('supervised').checked});
function stopDrive(){clearInterval(driveTimer);driveTimer=null;act('manual',{v:0,w:0})}
document.querySelectorAll('[data-drive]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);let d={v:b.dataset.drive==='forward'?.04:0,w:b.dataset.drive==='left'?.35:b.dataset.drive==='right'?-.35:0};act('manual',d);driveTimer=setInterval(()=>act('manual',d),100)};b.onpointerup=stopDrive;b.onpointercancel=stopDrive;b.onlostpointercapture=()=>{if(driveTimer)stopDrive()}});
window.addEventListener('blur',()=>{if(driveTimer)stopDrive()});document.addEventListener('keydown',e=>{if(e.key==='Escape')act('estop')});
function world(x,y){return [(x-grid.origin)/(grid.size*grid.resolution)*720,720-(y-grid.origin)/(grid.size*grid.resolution)*720]}
$('map').onclick=e=>{if(!grid)return;let r=e.currentTarget.getBoundingClientRect();let x=grid.origin+(e.clientX-r.left)/r.width*grid.size*grid.resolution;let y=grid.origin+(1-(e.clientY-r.top)/r.height)*grid.size*grid.resolution;selected=[x,y];$('x').value=x.toFixed(2);$('y').value=y.toFixed(2);$('locations').value='';$('coords').textContent=`Selected ${x.toFixed(2)}, ${y.toFixed(2)} m`;draw()};
function draw(){if(!grid||!state)return;const c=$('map').getContext('2d'),cell=720/grid.size;c.clearRect(0,0,720,720);let colors=['#0b1520','#385467','#d29c5d'];for(let y=0;y<grid.size;y++)for(let x=0;x<grid.size;x++){c.fillStyle=colors[grid.cells[y][x]];c.fillRect(x*cell,720-(y+1)*cell,cell+.4,cell+.4)}
function line(points,color){if(!points.length)return;c.beginPath();c.strokeStyle=color;c.lineWidth=3;points.forEach((p,i)=>{let q=world(...p);i?c.lineTo(...q):c.moveTo(...q)});c.stroke()}
line(state.trail,'#587891');line(state.path,'#46e7c0');for(let [name,p] of Object.entries(state.locations)){let q=world(...p);c.fillStyle='#dfedf7';c.fillRect(q[0]-3,q[1]-3,6,6);c.font='14px sans-serif';c.fillText(name,q[0]+8,q[1]-8)}
let p=state.pose,q=world(p.x,p.y);c.save();c.translate(...q);c.rotate(-p.yaw);c.fillStyle='#39edc1';c.beginPath();c.moveTo(13,0);c.lineTo(-9,-8);c.lineTo(-9,8);c.closePath();c.fill();c.restore();if(selected){let s=world(...selected);c.strokeStyle='#fff';c.beginPath();c.arc(...s,8,0,Math.PI*2);c.stroke()}}
let busy=false;async function refresh(){if(!token||busy)return;busy=true;try{state=await(await api('state')).json();$('mode').textContent=state.mode.toUpperCase()+(state.armed?' · ARMED':' · DISARMED');$('state').textContent=state.state.replaceAll('_',' ');$('voltage').textContent=state.voltage==null?'—':state.voltage.toFixed(2)+' V';$('current').textContent=state.current==null?'—':state.current.toFixed(2)+' A';$('confidence').textContent=Math.round(state.confidence*100)+'%';$('reason').textContent=state.reason;$('gates').textContent=[...state.gates,...(state.sensor_fault?[state.sensor_fault]:[])].join(' · ');let old=$('locations').value;let names=Object.keys(state.locations);if(JSON.stringify(names)!==$('locations').dataset.names){$('locations').replaceChildren(new Option('Use selected map point',''),...names.map(n=>new Option(n,n)));$('locations').dataset.names=JSON.stringify(names);$('locations').value=old}
$('queue').replaceChildren(...state.queue.map(q=>{let li=document.createElement('li');li.textContent=q.name+' ';let b=document.createElement('button');b.textContent='Remove';b.onclick=()=>act('cancel',{id:q.id});li.append(b);return li}));$('events').replaceChildren(...state.events.slice(0,25).map(e=>{let li=document.createElement('li'),t=document.createElement('time');t.textContent=e.time;li.append(t,document.createTextNode(e.message));return li}));draw()}catch(e){notice(e.message,true);$('mode').textContent='DISCONNECTED'}finally{busy=false}}
setInterval(refresh,500);setInterval(async()=>{if(!token)return;try{grid=await(await api('map')).json();draw()}catch{}},1500);
setInterval(async()=>{if(!token||state?.mode!=='hardware')return;try{let r=await api('camera');if(r.status===204)return;let url=URL.createObjectURL(await r.blob());$('camera').src=url;if(cameraURL)URL.revokeObjectURL(cameraURL);cameraURL=url}catch{}},500);refresh();
